apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zlfg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0045-tenant/tkrw-pr712-0075-0045-app/devfile-sample-zlfg@sha256:51b55de572f7f486ad43627c7e318fbe46472fb291938ddfbbe0c9caca341318
        name: my-nodejs
        resources: {}
status: {}
